const mongoose = require("mongoose");

const slug = require("mongoose-slug-updater");

const Schema = mongoose.Schema;

const adSchema = new Schema(
  {
    adReference: { type: String, required: true },
    adStatus: {
      type: String,
      enum: ["En preparación", "Activo", "Inactivo"],
      default: "En preparación",
    },
    title: { type: String, required: true },
    slug: {
      type: String,
      slug: "title",
      unique: true,
      permanent: true,
    },
    showOnWeb: { type: Boolean, default: true },
    showOnWebOffMarket: { type: Boolean },
    featuredOnMain: { type: Boolean },
    featuredDrawings: { type: Boolean },
    sendedTo: [
      {
        contactRequestName: { type: String },
        contactRequestEmail: { type: String },
        requestReferenceId: { type: Number },
        sendedAt: { type: String },
      },
    ],
    adDirection: {
      address: {
        street: { type: String, required: true },
        directionNumber: { type: String, required: true },
        directionFloor: { type: String },
      },
      postalCode: { type: String },
      city: { type: String },
      country: { type: String },
    },
    internalComments: { type: String },
    adType: { type: [String], enum: ["Alquiler", "Venta"], required: true },
    gvOperationClose: {
      type: String,
      enum: ["Vendido", "Alquilado", ""],
      default: "",
    },
    owner: { type: mongoose.Types.ObjectId, ref: "contacts" },
    consultant: { type: mongoose.Types.ObjectId, ref: "consultants" },
    realStatePortals: { type: [String], enum: ["Idealista", "Otros portales"] },
    adBuildingType: {
      type: [String],
      enum: [
        "Casa",
        "Piso",
        "Bajo",
        "Parcela",
        "Ático",
        "Oficina",
        "Edificio",
        "Local",
        "Campo Rústico",
        "Activos singulares",
        "Costa",
        "Nave",
        "Suelo",
        "Finca",
        "Casa de Campo",
        "Activo Singular",
      ],
      required: true,
    },
    zone: [{ type: mongoose.Types.ObjectId, ref: "zones" }],
    distrito: { type: String, index: true },
    barrio: { type: String, index: true },
    department: {
      type: String,
      enum: [
        "Patrimonio",
        "Residencial",
        "Otros",
        "Campos Rústicos & Activos Singulares",
        "Costa",
      ],
      required: true,
    },
    webSubtitle: { type: String },
    buildSurface: { type: Number },
    plotSurface: { type: Number },
    m2StorageSpace: { type: Number },
    m2Terrace: { type: Number },
    floor: { type: String },
    disponibility: { type: String },
    profitability: { type: Boolean, default: false },
    profitabilityValue: { type: Number, default: 0 },
    surfacesBox: [
      {
        id: { type: Number },
        surfaceFloor: { type: String },
        surfaceUse: { type: String },
        metersAvailables: { type: String },
        metersPrice: { type: String },
        surfaceDisponibility: { type: String },
      },
    ],
    sale: {
      saleValue: { type: Number },
      saleShowOnWeb: { type: Boolean },
      saleRepercussionM2: { type: String },
      saleRepercussionM2ShowOnWeb: { type: Boolean },
    },
    rent: {
      rentValue: { type: Number },
      rentShowOnWeb: { type: Boolean },
    },
    monthlyRent: { type: Number },
    expenses: { type: Number },
    expensesIncluded: { type: Number },
    communityExpenses: {
      expensesValue: { type: Number },
      expensesShowOnWeb: { type: Boolean },
    },
    ibi: {
      ibiValue: { type: Number },
      ibiShowOnWeb: { type: Boolean },
    },
    trashFee: {
      trashFeeValue: { type: Number },
      trashFeeShowOnWeb: { type: Boolean, default: false },
    },
    buildingYear: { type: String },
    quality: {
      bedrooms: { type: Number },
      bathrooms: { type: Number },
      parking: { type: Number },
      reformed: { type: Boolean },
      toReform: { type: Boolean },
      indoorPool: { type: Number },
      outdoorPool: { type: Number },
      jobPositions: { type: Number },
      subway: { type: String },
      bus: { type: String },
      storageRoom: { type: String },
      others: {
        lift: { type: Boolean },
        dumbwaiter: { type: Boolean },
        liftTruck: { type: Boolean },
        airConditioning: { type: Boolean },
        centralHeating: { type: Boolean },
        individualHeating: { type: Boolean },
        concierge: { type: Boolean },
        mixedBuilding: { type: Boolean },
        subfloorHeating: { type: Boolean },
        indoorAlarm: { type: Boolean },
        outdoorAlarm: { type: Boolean },
        fullHoursSecurity: { type: Boolean },
        gunRack: { type: Boolean },
        strongBox: { type: Boolean },
        well: { type: Boolean },
        homeAutomation: { type: Boolean },
        centralVacuum: { type: Boolean },
        padelCourt: { type: Boolean },
        tennisCourt: { type: Boolean },
        terrace: { type: Boolean },
        storage: { type: Boolean },
        swimmingPool: { type: Boolean },
        indoorPoolCheck: { type: Boolean },
        outdoorPoolCheck: { type: Boolean },
        outdoorPoolClimatized: { type: Boolean },
        garage: { type: Boolean },
        falseCeiling: { type: Boolean },
        raisedFloor: { type: Boolean },
        qualityBathrooms: { type: Boolean },
        freeHeight: { type: Boolean },
        smokeOutlet: { type: Boolean },
        accessControl: { type: Boolean },
        furnished: { type: Boolean },
        implanted: { type: Boolean },
        separateEntrance: { type: Boolean },
        exclusiveOfficeBuilding: { type: Boolean },
        classicBuilding: { type: Boolean },
        coworking: { type: Boolean },
        accessiblePMR: { type: Boolean },
        agricultural: { type: Boolean },
        hunting: { type: Boolean },
        forestry: { type: Boolean },
        livestock: { type: Boolean },
        rusticOther: { type: Boolean },
        warehouses: { type: Boolean },
        secondaryHousing: { type: Boolean },
        equestrianFacilities: { type: Boolean },
        electricSupply: { type: Boolean },
        pond: { type: Boolean },
        reservoir: { type: Boolean },

        // NUEVOS CAMPOS GENRALES
        recess: { type: Boolean },
        fenced: { type: Boolean },
        porch: { type: Boolean },
        fireplace: { type: Boolean },
        gym: { type: Boolean },

        modernStyle: { type: Boolean },
        classicStyle: { type: Boolean },
        andaluzStyle: { type: Boolean },
        seaViews: { type: Boolean },
        panoramicView: { type: Boolean },

        golfCourseView: { type: Boolean },
        mountainView: { type: Boolean },
        privateGarden: { type: Boolean },
        solarium: { type: Boolean },
        outdoorKitchen: { type: Boolean },

        carPort: { type: Boolean },
        lounge: { type: Boolean },
        firePlace: { type: Boolean },
        showKitchen: { type: Boolean },
        dirtyKitchen: { type: Boolean },

        spa: { type: Boolean },
        movieTheater: { type: Boolean },
        wineCellar: { type: Boolean },
        laundry: { type: Boolean },
        brandedDesign: { type: Boolean },

        conciergeService: { type: Boolean },
        gatedCommunity: { type: Boolean },
        panicRoom: { type: Boolean },
        newConstruction: { type: Boolean },
        goodConservation: { type: Boolean },
      },
    },
    description: {
      web: { type: String },
      emailPDF: { type: String },
      distribution: { type: String },
    },
    changesHistory: [
      {
        type: {
          type: String,
          enum: [
            "CREATION",
            "PRICE_CHANGE",
            "OWNER_CHANGE",
            "ADTYPE_CHANGE",
            "GV_OPERATION_CHANGE",
            "OTHER",
          ],
          required: true,
        },
        field: { type: String },
        oldValue: { type: Schema.Types.Mixed },
        newValue: { type: Schema.Types.Mixed },
        date: { type: Date, default: Date.now },
        consultant: {
          _id: { type: mongoose.Types.ObjectId, ref: "consultants" },
          fullName: { type: String },
        },
        note: { type: String },
      },
    ],
    images: {
      main: { type: String },
      blueprint: { type: Array },
      others: { type: Array },
      media: { type: String },
    },
  },
  {
    timestamps: true,
  },
);

adSchema.plugin(slug);

const Ad = mongoose.model("ads", adSchema);

module.exports = Ad;
